site_name: PipelineDocs
site_url: https://pipelinedocs.readthedocs.io/en/latest/
nav:
  - Introduction: index.md
  - General Information:
    - Running Snakemake pipelines: deploy.md
    - Snakemake on Yale HPC: simon.md
    - Alternative deployment strategies: alt.md
    - Tips and tricks: pragmatism.md
  - Pipeline Introductions:
    - bam2bakR: intro/bam2bakR_i.md
    - PROseq_etal: intro/proseq_i.md
    - THE_Aligner: intro/aligner_i.md
  - Pipeline Output:
    - bam2bakR's Output: bam2bakR_o.md
    - PROseq_etal's Output: proseq_o.md
    - THE_Aligner's Output: aligner_o.md
  - Configuration:
    - bam2bakR's config.yaml: configuration/bam2bakR_c.md
    - PROseq_etal's config.yaml: configuration/proseq_c.md
    - THE_Aligner's config.yaml: configuration/aligner_c.md
  - Pipeline architecture:
    - bam2bakR's layout: architecture/bam2bakR_a.md
    - PROseq_etal's layout: architecture/proseq_a.md
    - THE_Aligner's layout: architecture/aligner_a.md
  - Miscellaneous pipeline-specific info:
    - Making color-coded tracks with bam2bakR: tracks.md
  - FAQs:
    - bam2bakR: faqs/bam2bakR_f.md
    - PROseq_etal: faqs/proseq_f.md
    - THE_Aligner: faqs/aligner_f.md
theme: readthedocs
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets