site_name: PipelineDocs
site_url: https://pipelinedocs.readthedocs.io/en/latest/
nav:
  - Introduction: index.md
  - General Information:
    - Running Snakemake pipelines: deploy.md
    - Snakemake on Yale HPC: simon.md
    - Alternative deployment strategies: alt.md
    - Tips and tricks: pragmatism.md
  - bam2bakR:
    - Intro to bam2bakR: bam2bakR/intro.md
    - Configuring bam2bakR: bam2bakR/configuration.md
    - bam2bakR's Output: bam2bakR/output.md
    - bam2bakR's Architecture: bam2bakR/architecture.md
    - FAQs: bam2bakR/faqs.md
  - PROseq_etal:
    - Intro to PROseq_etal: proseq/intro.md
    - Configuring PROseq_etal: proseq/configuration.md
    - PROseq_etal's Output: proseq/output.md
    - PROseq_etal's Architecture: proseq/architecture.md
    - FAQs: proseq/faqs.md
  - THE_Aligner:
    - Intro to THE_Aligner: aligner/intro.md
    - Configuring THE_Aligner: aligner/configuration.md
    - THE_Aligner's Output: aligner/output.md
    - THE_Aligner's Architecture: aligner/architecture.md
    - FAQs: aligner/faqs.md
  - Miscellaneous pipeline-specific info:
    - Making color-coded tracks with bam2bakR: tracks.md
theme: readthedocs
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets