site_name: PipelineDocs
site_url: https://pipelinedocs.readthedocs.io/en/latest/
nav:
  - Introduction: index.md
  - General Information:
    - Running Snakemake pipelines: deploy.md
    - Snakemake on Yale HPC: simon.md
    - Alternative deployment strategies: alt.md
    - Tips and tricks: pragmatism.md
  - bam2bakR:
    - Intro to bam2bakR: bam2bakR/intro.md
    - Configuring bam2bakR: bam2bakR/configuration.md
    - bam2bakR's Output: bam2bakR/output.md
    - FAQs: bam2bakR/faqs.md
    - Color-coded tracks with bam2bakR: tracks.md
  - PROseq_etal:
    - Intro to PROseq_etal: proseq/intro.md
    - Configuring PROseq_etal: proseq/configuration.md
    - PROseq_etal's Output: proseq/output.md
    - FAQs: proseq/faqs.md
  - THE_Aligner:
    - Intro to THE_Aligner: aligner/intro.md
    - Configuring THE_Aligner: aligner/configuration.md
    - THE_Aligner's Output: aligner/output.md
    - FAQs: aligner/faqs.md
theme: 
  name: readthedocs
  navigation_depth: 5
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets