site_name: PROseq_etal
site_url: https://.readthedocs.io/en/latest/
nav:
  - Introduction: index.md
  - Pipelines:
    - bam2bakR: intro/bam2bakR_i.md
    - PROseq_etal: intro/proseq_i.md
    - THE_Aligner: intro/aligner_i.md
  - Running Snakemake pipelines: deploy.md
  - Snakemake on Yale HPC: simon.md
  - Alternative deployment strategies: alt.md
  - Output:
    - bam2bakR Output: bam2bakR_o.md
    - PROseq_etal Output: proseq_o.md
    - THE_Aligner Output: aligner_o.md
  - Configuration:
    - bam2bakR: configuration/bam2bakR_c.md
    - PROseq_etal: configuration/proseq_c.md
    - THE_Aligner: configuration/aligner_c.md
  - Pipeline architecture:
    - bam2bakR: architecture/bam2bakR_a.md
    - PROseq_etal: architecture/proseq_a.md
    - THE_Aligner: architecture/aligner_a.md
  - General information: pragmatism.md
  - Miscellaneous pipeline-specific info:
    - Making color-coded tracks with bam2bakR: tracks.md
  - FAQs:
    - bam2bakR: faqs/bam2bakR_f.md
    - PROseq_etal: faqs/proseq_f.md
    - THE_Aligner: faqs/aligner_f.md
theme: readthedocs
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets